image: gitlab.zengenti.com:4567/ops/zengenti-dind:latest

stages:
  - latest-build
  - storybook-latest-build
  - live-build
  # - development-release-build
  - automated-tests
  - push-to-contensis

variables:
  DOCKER_DRIVER: overlay2
  STORYBOOK: ''
  APP_BUILDER_IMAGE: '$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME/app-builder'
  APP_IMAGE: '$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME/app'
  STORYBOOK_BUILDER_IMAGE: '$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME/storybook-builder'
  STORYBOOK_IMAGE: '$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME/storybook'
  MASTER_APP: '$CI_REGISTRY_IMAGE/master/app'
  DEVELOP_APP: '$CI_REGISTRY_IMAGE/develop/app'

services:
  - docker:dind

build-latest-code:
  stage: latest-build
  except:
    - tags
  script:
    - docker pull $APP_BUILDER_IMAGE:latest || true
    - echo "{\"commitRef\":\"$CI_COMMIT_SHA\",\"pipelineIID\":\"$CI_PIPELINE_IID\",\"pipelineUrl\":\"$CI_PIPELINE_URL\",\"buildNo\":\"$CI_PIPELINE_ID\",\"branchName\":\"$CI_COMMIT_REF_NAME\",\"registryImage\":\"$CI_REGISTRY_IMAGE\"}" > version.json
    - docker build --force-rm --cache-from $APP_BUILDER_IMAGE:latest -t $APP_BUILDER_IMAGE:latest -f docker/nodebuilder.DockerFile .
    - docker push $APP_BUILDER_IMAGE:latest
    - docker pull $APP_IMAGE:latest || true
    - docker build --force-rm --cache-from $APP_IMAGE:latest -t $APP_IMAGE:latest --build-arg builder_image=$APP_BUILDER_IMAGE:latest -f docker/ci-build.DockerFile .
    - docker push $APP_IMAGE:latest
  environment:
    name: latest
    url: http://dev.preview.$CI_PROJECT_NAME.contensis.cloud

build-storybook:
  stage: storybook-latest-build
  except:
    - tags
  script:
    - docker pull $STORYBOOK_BUILDER_IMAGE:latest || true
    - docker build --compress --force-rm --cache-from $STORYBOOK_BUILDER_IMAGE:latest -t $STORYBOOK_BUILDER_IMAGE:latest -f docker/storybook-builder.DockerFile .
    - docker push $STORYBOOK_BUILDER_IMAGE:latest
    - docker build --compress --force-rm -t $STORYBOOK_IMAGE:latest --build-arg builder_image=$STORYBOOK_BUILDER_IMAGE:latest -f  docker/storybook-http.DockerFile .
    - docker push $STORYBOOK_IMAGE:latest
  environment:
    name: storybook
    url: http://storybook.latest.$CI_PROJECT_NAME.contensis.cloud

run-automated-tests:
  stage: automated-tests
  image:
    name:
      cypress/included:6.4.0
      # cypress/included images have entrypoint set to "cypress"
      # which conflicts with GitLab CI wrapper shell script
    entrypoint: ['']
  services:
    - name: $APP_IMAGE:latest
      alias: site-to-test
  except:
    - tags
    - ^release-.*$
  script:
    - npm install typescript
    - mkdir cypress-context
    - mkdir cypress-context/cypress
    - cp cypress.json cypress-context
    - cp -R cypress cypress-context/.
    - CYPRESS_BASE_URL=http://site-to-test:3001 cypress run --project ./cypress-context --record --key 04ecba8e-021d-4d94-a421-617e4fb2368c

build-live-code-for-production:
  stage: live-build
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^release-.*$/
  except:
    - branches
  script:
    - docker pull "$MASTER_APP:latest"
    - docker tag "$MASTER_APP:latest" "$MASTER_APP:release"
    - docker push "$MASTER_APP:release"
    - docker tag "$MASTER_APP:latest" "$MASTER_APP:$CI_COMMIT_TAG"
    - docker push "$MASTER_APP:$CI_COMMIT_TAG"

  environment:
    name: live
    url: http://preview.$CI_PROJECT_NAME.contensis.cloud

push-to-contensis:
  only:
    - master
  stage: push-to-contensis
  image: gitlab.zengenti.com:4567/ops/contensis-cli:latest
  variables:
    GIT_STRATEGY: none
  script:
    - contensis-cli add-instance --alias=zenhub --id=2db505bd-cab4-46f6-adc5-d2acd0da536c --secret=5943ce8838984f9480cf4f78de84d7ad-d53d76e39f88414d9c8ec2ca2cf757cd-eb11a880c53e4bc295de85205ec5c201
    - contensis-cli default-project leif
    - contensis-cli push block --id="main-site" --imageUri="$MASTER_APP" --imageTag="$CI_COMMIT_TAG" --branch="master" --sourceProvider="GitlabSelfHosted" --repositoryUrl="$CI_REPOSITORY_URL" --commitId="$CI_COMMIT_SHORT_SHA" --commitMessage="$CI_COMMIT_MESSAGE" --commitDateTime="$CI_COMMIT_TIMESTAMP" --authorEmail="$GITLAB_USER_EMAIL" --committerEmail="$GITLAB_USER_EMAIL" --autoRelease


# build-live-code-for-development:
#   stage: development-release-build
#   only:
#     refs:
#       - tags
#     variables:
#       - $CI_COMMIT_TAG =~ /^devrelease-.*$/
#   script:
#     - docker pull "$DEVELOP_APP:latest"
#     - docker tag "$DEVELOP_APP:latest" "$DEVELOP_APP:release"
#     - docker push "$DEVELOP_APP:release"
#   environment:
#     name: live
#     url: http://preview.$CI_PROJECT_NAME.contensis.cloud
