name: Docker - Build and push latest

on:
  push:
    branches: ['**']
    tags-ignore: ['release-*']
  pull_request:
    branches: ['**']

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  APP_IMAGE: ghcr.io/${{ github.repository }}/${{ github.ref_name }}/app
  STORYBOOK_IMAGE: ghcr.io/${{ github.repository }}/${{ github.ref_name }}/storybook

jobs:
  build-latest:
    name: Docker build latest code
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image-uri: ${{ steps.build.outputs.image-uri }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry except on PR
      - name: Log into container registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image, tag and push to registry
        id: build
        run: |
          BUILD_IMAGE=${{ env.APP_IMAGE }}:build-${{ github.run_number }} && \
            LATEST_IMAGE=${{ env.APP_IMAGE }}:latest && \
            BUILDER_IMAGE=${{ env.APP_IMAGE }}:builder
          if [[ "$(docker pull $BUILDER_IMAGE && BUILDER_IMAGE_ARG=$BUILDER_IMAGE || echo 1)" != "1" && "$(docker pull $LATEST_IMAGE && APP_IMAGE_ARG=$LATEST_IMAGE || echo 0)" == "0" ]]; then
            echo "Builder image exists: $BUILDER_IMAGE"; 
          fi
          echo "{\"commitRef\":\"${{ github.sha }}\",\"pipelineIID\":\"${{ github.run_id }}\",\"pipelineUrl\":\"${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}\",\"buildNo\":\"${{ github.run_number }}\",\"branchName\":\"${{ github.ref_name }}\",\"registryImage\":\"${{ env.APP_IMAGE }}\"}" > version.json
          docker build -t $BUILDER_IMAGE --cache-from $BUILDER_IMAGE --build-arg builder_image=$BUILDER_IMAGE_ARG --target prepare -f docker/build.Dockerfile .
          docker build -t $LATEST_IMAGE -t $BUILD_IMAGE --cache-from $LATEST_IMAGE --build-arg app_image=$APP_IMAGE_ARG --build-arg builder_image=$BUILDER_IMAGE -f docker/build.Dockerfile .
          docker push --all-tags ${{ env.APP_IMAGE }}
          echo "image-uri=$BUILD_IMAGE" >> $GITHUB_OUTPUT

  push-app-block:
    name: Push Contensis block
    needs: build-latest
    uses: ./.github/workflows/push-block.yml
    secrets: inherit
    with:
      block-id: leif-website
      image-uri: ${{ needs.build-latest.outputs.image-uri }}
      tag-repo: true

  build-storybook:
    name: Docker build storybook
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image-uri: ${{ steps.build.outputs.image-uri }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry except on PR
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image, tag and push to registry
        id: build
        run: |
          BUILDER_IMAGE=${{ env.STORYBOOK_IMAGE }}:builder && BUILDER_IMAGE_ARG=$BUILDER_IMAGE && LATEST_IMAGE=${{ env.STORYBOOK_IMAGE }}:latest && BUILD_IMAGE=${{ env.STORYBOOK_IMAGE }}:build-${{ github.run_number }}
          if [ "$(docker pull $BUILDER_IMAGE || echo 1)" == "1" ]; then BUILDER_IMAGE_ARG=$BUILDER_BASE; else echo "Builder image exists: $BUILDER_IMAGE"; fi
          docker build -t $BUILDER_IMAGE --cache-from $BUILDER_IMAGE --build-arg builder_image=$BUILDER_IMAGE_ARG --target prepare -f docker/storybook.Dockerfile .
          docker build -t $LATEST_IMAGE -t $BUILD_IMAGE --build-arg builder_image=$BUILDER_IMAGE -f docker/storybook.Dockerfile .
          docker push --all-tags ${{ env.STORYBOOK_IMAGE }}
          echo "image-uri=$BUILD_IMAGE" >> $GITHUB_OUTPUT

  push-storybook-block:
    name: Push Contensis block
    needs: build-storybook
    secrets: inherit
    uses: ./.github/workflows/push-block.yml
    with:
      block-id: leif-storybook
      image-uri: ${{ needs.build-storybook.outputs.image-uri }}
      auto-release: true
